### ISSUE TITLE
missing workflow figure?

### ISSUE THREAD

**Issue by janisshin** [EPFL-LCSB/skimpy#13]
This may be a trivial correction, but may helpful for any other outsiders looking at your code. 

I was looking through [skimpy/tutorials/ORACLE/tutorial_toy.py](https://github.com/EPFL-LCSB/skimpy/blob/master/tutorials/ORACLE/tutorial_toy.py) and on line 53, it says "A simplified version of the workflow presented in figure S9." S9 does not exist in the [supplementary material](https://www.biorxiv.org/content/10.1101/2022.01.17.476618v1.supplementary-material). Did you mean S8? Thanks.

**Comment by weilandtd** [comment]
@janisshin, Thank you for your comment. The code is revised to reflect changes that were part of the revision process. We are currently in the process of reviewing if an updated version of the paper can be posted while not violating the submission protocol. Should it be possible to post an update to bioRxiv of the current state of the paper we will do so as soon as possible.
