### ISSUE TITLE
No module named 'skimpy.nullspace' 

### ISSUE THREAD

**Issue by SharplessSword** [EPFL-LCSB/skimpy#14]
Dear developers,

i meet the same error with a closed [issue](https://github.com/EPFL-LCSB/skimpy/issues/10), but i can't solve it until i'm frustrated.
Here is a list of my procedure:
1.install minicoda and execute
```
conda config --add channels bioconda
conda config --add channels conda-forge
conda config --set channel_priority strict
conda create --name skimpy-env python=3.8
conda activate skimpy-env
conda install -c weilandtd skimpy
```
one by one
2.create a new python file named test_demo.py at the root directory skimpy/, and copy the Quick start code into it
3. `python3 test_demo.py`  try to run it
4. then  the error happened
```
../skimpy/skimpy/analysis/mca/utils.py", line 47, in <module>
    from skimpy.nullspace import left_integer_nullspace
ModuleNotFoundError: No module named 'skimpy.nullspace'
``` 
Is there some important step i missed?Or i need to show more details?

Gao

**Comment by weilandtd** [comment]
Hi Gao,

to solve your problem could you give us more information on the system you installed the software? 

skimpy.nullspace is a precompiled dependency that should only be missing if you installed it with pip and one of the following dependencies is not installed properly: GCC gfortran libsundials-dev libflint-dev libgmp-dev

My best guess is right now that python3 is not your conda python: you can easily check this by "which python3" 
If you are in an activated conda environment "python" should be linked to your conda python version.

**Comment by weilandtd** [comment]
@SharplessSword  Any updates on your problem?

**Comment by weilandtd** [comment]
Closed due inactivity
