### ISSUE TITLE
Comment out in mechanisms

### ISSUE THREAD

**Issue by teisnotte** [EPFL-LCSB/skimpy#16]
Hello Daniel,

It seems this commit with the new mechanism are giving problems with loading the model, are those comments out useful? Could you check? I comment in the code and it works again. 
https://github.com/EPFL-LCSB/skimpy/commit/627e2ca7805f7a7ee18ed7280f729ce8d298498c

**Comment by weilandtd** [comment]
Hey @teisnotte sorry for the late reply. But could you post a description of the error?
