### ISSUE TITLE
Installing skimpy on Ubuntu 21.10

### ISSUE THREAD

**Issue by eladnoor** [EPFL-LCSB/skimpy#5]
Hello,

I just wanted to share my solutions for installing `skimpy` on Ubuntu 21.10 from source.

First of all, using `pip install skimpy` doesn't work because it points to a different package: [aeturrell/skimpy](https://github.com/aeturrell/skimpy). Installing it from source (`pip install -e .`) was possible, but only after a bit of struggling with dependencies:

- I had to install these using the package manager: `sudo apt install cython3 gfortran libsundials-dev libflint-dev`
- I had to change the version of `sckits.odes` to 2.6.3 (latest) in `skimpy/setup.py` since the indicated version (2.4.1) couldn't be installed on my machine. As far as I can tell, it works well with the newer version.
- Finally, I'm not 100% sure about this, but installing `cython` via `pip` before installing `scikits.odes` is required since it seems the dependency is not resolved correctly by `pip`.

After this `pip install -e .` worked and I managed to run the tests without errors.

**Comment by weilandtd** [comment]
Hey Elad,

Thank you very much for the feedback! I will think about how to make the pip install work.

- I will add the installation requirements to include these dependencies. 
- Great to hear that it works with the latest `scikits.odes` , I will directly update the requirements (for a while the `scikits.odes` package was deprecated thus we had to rely on this older version) 
- Just to make sure did you install the `scikits.odes` according to the [documentation](https://scikits-odes.readthedocs.io/en/stable/installation.html)? I know that this package is a bit of a pain to install as it requires the installation of the [sundials solvers](https://computing.llnl.gov/projects/sundials) from source. We have a [script](https://github.com/EPFL-LCSB/skimpy/blob/master/docker/utils/install_sundials.sh) to install for the docker build.

**Comment by eladnoor** [comment]
I did follow the `scikits.odes` documentation, but installed Sundials using the Debian package (`libsundails-dev`) instead of from source. As far as I can tell, it worked.

Basically, with `apt` and `pip` together I managed to install everything without requiring any source code installations.

**Comment by weilandtd** [comment]
Wow, that is great! Thank you so much for that valuable feedback.
